//! Runtime Service and Crash Watchdog for Hadron swarm.
//!
//! Monitors background processes managed by [`ProcessManager`], scans log ring buffers for
//! runtime crashes, panics, unhandled exceptions, and port conflicts, probes HTTP health endpoints,
//! and synthesizes actionable self-healing remediation suggestions.
//!
//! **Invariants:**
//! 1. Jailed process supervision: Inspects only processes managed within the worktree `ProcessManager`.
//! 2. Local origin bounds: HTTP health probes are strictly confined to loopback (`127.0.0.1`, `localhost`).
//! 3. Resilient diagnostics: Produces actionable remediation advice even on silent or hard crashes.

use std::fmt;
use std::time::Duration;

use serde::{Deserialize, Serialize};

use crate::file::ForgeError;
use crate::process::ProcessManager;

/// Health classification for a monitored service.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ServiceHealthStatus {
    Healthy,
    Degraded,
    Crashed,
    Hung,
    Unknown,
}

impl fmt::Display for ServiceHealthStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ServiceHealthStatus::Healthy => write!(f, "healthy"),
            ServiceHealthStatus::Degraded => write!(f, "degraded"),
            ServiceHealthStatus::Crashed => write!(f, "crashed"),
            ServiceHealthStatus::Hung => write!(f, "hung"),
            ServiceHealthStatus::Unknown => write!(f, "unknown"),
        }
    }
}

/// A specific crash, exception, or port conflict detected by the watchdog.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WatchdogFinding {
    pub kind: String,
    pub line: String,
    pub suggestion: String,
}

/// Configuration parameters for service health inspection.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WatchdogConfig {
    #[serde(default)]
    pub process_id: Option<u64>,
    #[serde(default)]
    pub health_url: Option<String>,
    #[serde(default)]
    pub error_burst_threshold: Option<usize>,
    #[serde(default)]
    pub timeout_ms: Option<u64>,
}

/// Comprehensive health and diagnostic report generated by the watchdog.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WatchdogReport {
    pub status: ServiceHealthStatus,
    pub is_running: bool,
    pub exit_code: Option<i32>,
    pub findings: Vec<WatchdogFinding>,
    pub remediation_hint: Option<String>,
    pub summary: String,
}

/// Evaluates background process health, scans log streams, and probes endpoints.
pub async fn check_service_health(
    process_manager: &ProcessManager,
    config: &WatchdogConfig,
) -> Result<WatchdogReport, ForgeError> {
    let procs = process_manager.list().await;

    let target_proc = if let Some(id) = config.process_id {
        procs.into_iter().find(|p| p.id == id)
    } else {
        procs.into_iter().next()
    };

    let Some(proc_summary) = target_proc else {
        return Ok(WatchdogReport {
            status: ServiceHealthStatus::Unknown,
            is_running: false,
            exit_code: None,
            findings: vec![],
            remediation_hint: Some("No matching background process found to monitor.".into()),
            summary: "Watchdog: No target process active in ProcessManager.".into(),
        });
    };

    let log_content = process_manager
        .get_logs(proc_summary.id, Some(200), None)
        .await
        .unwrap_or_default();

    let mut findings = scan_logs_for_anomalies(&log_content);

    // If exit code indicates non-zero failure
    if let Some(code) = proc_summary.exit_code {
        if code != 0 {
            findings.push(WatchdogFinding {
                kind: "NON_ZERO_EXIT".into(),
                line: format!("Process exited with failure exit code: {code}"),
                suggestion: "Inspect stderr traces above to fix fatal initialization crash".into(),
            });
        }
    }

    // Health URL probe
    let mut probe_passed = true;
    if let Some(url_str) = &config.health_url {
        validate_local_origin(url_str)?;
        let timeout = Duration::from_millis(config.timeout_ms.unwrap_or(2000));
        match probe_http_endpoint(url_str, timeout).await {
            Ok(true) => {
                probe_passed = true;
            }
            Ok(false) | Err(_) => {
                probe_passed = false;
                findings.push(WatchdogFinding {
                    kind: "HEALTH_ENDPOINT_UNRESPONSIVE".into(),
                    line: format!("Health probe to {url_str} timed out or returned error status"),
                    suggestion: "Verify server port listening and route registration".into(),
                });
            }
        }
    }

    let status = if !proc_summary.running {
        if proc_summary.exit_code == Some(0) && (config.health_url.is_none() || probe_passed) {
            ServiceHealthStatus::Healthy
        } else {
            ServiceHealthStatus::Crashed
        }
    } else if !findings.is_empty() || !probe_passed {
        ServiceHealthStatus::Degraded
    } else {
        ServiceHealthStatus::Healthy
    };

    let remediation_hint = synthesize_remediation_hint(&status, &findings, proc_summary.exit_code);

    let summary = format!(
        "Service #{}: {} [{}] (exit: {:?}, {} anomaly finding(s))",
        proc_summary.id,
        proc_summary.program,
        status,
        proc_summary.exit_code,
        findings.len()
    );

    Ok(WatchdogReport {
        status,
        is_running: proc_summary.running,
        exit_code: proc_summary.exit_code,
        findings,
        remediation_hint,
        summary,
    })
}

/// Scans raw process logs for panics, tracebacks, port collisions, and unhandled rejections.
fn scan_logs_for_anomalies(logs: &str) -> Vec<WatchdogFinding> {
    let mut findings = vec![];

    for line in logs.lines() {
        let trimmed = line.trim();

        // 1. Rust Panics
        if trimmed.contains("panicked at") || trimmed.contains("stack backtrace:") {
            findings.push(WatchdogFinding {
                kind: "PANIC_STACKTRACE".into(),
                line: trimmed.to_string(),
                suggestion: "Investigate unwrap()/expect() or bounds assertion in Rust binary".into(),
            });
        }

        // 2. Node / JS Errors
        if trimmed.contains("UnhandledPromiseRejection")
            || trimmed.contains("TypeError:")
            || trimmed.contains("ReferenceError:")
            || trimmed.contains("SyntaxError:")
            || trimmed.contains("Cannot find module")
        {
            findings.push(WatchdogFinding {
                kind: "UNHANDLED_EXCEPTION_NODE".into(),
                line: trimmed.to_string(),
                suggestion: "Check module imports, null reference checks, and package.json dependencies".into(),
            });
        }

        // 3. Python Tracebacks
        if trimmed.contains("Traceback (most recent call last):")
            || trimmed.contains("ModuleNotFoundError:")
            || trimmed.contains("ImportError:")
        {
            findings.push(WatchdogFinding {
                kind: "PYTHON_TRACEBACK".into(),
                line: trimmed.to_string(),
                suggestion: "Verify Python environment packages and import paths in pyproject.toml".into(),
            });
        }

        // 4. Port Conflicts & Networking
        if trimmed.contains("EADDRINUSE") || trimmed.contains("address already in use") {
            findings.push(WatchdogFinding {
                kind: "PORT_CONFLICT".into(),
                line: trimmed.to_string(),
                suggestion: "Port is occupied by another process; select an alternate port or terminate existing listener".into(),
            });
        }

        if trimmed.contains("ECONNREFUSED") || trimmed.contains("Connection refused") {
            findings.push(WatchdogFinding {
                kind: "CONNECTION_REFUSED".into(),
                line: trimmed.to_string(),
                suggestion: "Underlying database or service dependency is not reachable on expected host/port".into(),
            });
        }
    }

    findings
}

/// Synthesizes high-level self-healing instruction based on detected issues.
fn synthesize_remediation_hint(
    status: &ServiceHealthStatus,
    findings: &[WatchdogFinding],
    exit_code: Option<i32>,
) -> Option<String> {
    match status {
        ServiceHealthStatus::Healthy => None,
        ServiceHealthStatus::Crashed => {
            if let Some(port_find) = findings.iter().find(|f| f.kind == "PORT_CONFLICT") {
                Some(format!("Self-healing: Rebind service to alternate available port ({})", port_find.line))
            } else if let Some(mod_find) = findings.iter().find(|f| f.kind.contains("MODULE") || f.kind.contains("IMPORT") || f.kind.contains("Cannot find module")) {
                Some(format!("Self-healing: Install missing dependency via hadron_forge_scaffold ({})", mod_find.line))
            } else if exit_code == Some(101) {
                Some("Self-healing: Rust binary panicked on startup; inspect assertions and fix unwrap sites".into())
            } else {
                Some("Self-healing: Inspect stderr output and restart service with corrected configuration".into())
            }
        }
        ServiceHealthStatus::Degraded => {
            if let Some(first) = findings.first() {
                Some(format!("Self-healing recommendation: {}", first.suggestion))
            } else {
                Some("Self-healing: Health probe failing; verify endpoint route handlers and server listen state".into())
            }
        }
        ServiceHealthStatus::Hung | ServiceHealthStatus::Unknown => {
            Some("Self-healing: Restart background service using hadron_forge_preview_launch".into())
        }
    }
}

/// Ensures probe target is restricted to loopback origin.
fn validate_local_origin(url_str: &str) -> Result<(), ForgeError> {
    if url_str.starts_with("http://127.0.0.1")
        || url_str.starts_with("http://localhost")
        || url_str.starts_with("http://[::1]")
        || url_str.starts_with("https://127.0.0.1")
        || url_str.starts_with("https://localhost")
    {
        Ok(())
    } else {
        Err(ForgeError::Rejected(format!(
            "Health probe URL {url_str} must be bound to localhost / 127.0.0.1"
        )))
    }
}

/// Connects to local endpoint via TCP / HTTP socket with timeout.
async fn probe_http_endpoint(url_str: &str, timeout: Duration) -> Result<bool, ForgeError> {
    let port = if let Some(rest) = url_str.strip_prefix("http://127.0.0.1:")
        .or_else(|| url_str.strip_prefix("http://localhost:"))
    {
        let port_part = rest.split('/').next().unwrap_or("80");
        port_part.parse::<u16>().unwrap_or(80)
    } else {
        80
    };

    let addr = format!("127.0.0.1:{port}");
    match tokio::time::timeout(timeout, tokio::net::TcpStream::connect(addr)).await {
        Ok(Ok(_stream)) => Ok(true),
        _ => Ok(false),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[tokio::test]
    async fn watchdog_detects_panics_and_crashes_with_remediation() {
        let temp = tempdir().unwrap();
        let root = Root::new(temp.path());
        let pm = ProcessManager::new(root);

        // Spawn a short-lived process that exits with 0
        let pid = pm.spawn("git", &["--version"], None).await.unwrap();

        tokio::time::sleep(Duration::from_millis(150)).await;

        let config = WatchdogConfig {
            process_id: Some(pid),
            health_url: None,
            error_burst_threshold: Some(3),
            timeout_ms: Some(100),
        };

        let report = check_service_health(&pm, &config).await.unwrap();
        assert_eq!(report.status, ServiceHealthStatus::Healthy);
        assert_eq!(report.exit_code, Some(0));

        // Test log anomaly scanner directly
        let panic_logs = "Starting server...\nthread 'main' panicked at 'called `Option::unwrap()` on a `None` value'\nstack backtrace:";
        let findings = scan_logs_for_anomalies(panic_logs);
        assert_eq!(findings.len(), 2);
        assert_eq!(findings[0].kind, "PANIC_STACKTRACE");

        let port_logs = "Error: listen EADDRINUSE: address already in use :::3000";
        let port_findings = scan_logs_for_anomalies(port_logs);
        assert_eq!(port_findings.len(), 1);
        assert_eq!(port_findings[0].kind, "PORT_CONFLICT");

        let hint = synthesize_remediation_hint(&ServiceHealthStatus::Crashed, &port_findings, Some(1));
        assert!(hint.unwrap().contains("alternate available port"));
    }
}
