[package]
name = "hadron-gluon"
version = "0.1.0"
edition = "2021"

[dependencies]
hadron-lattice = { path = "../hadron-lattice" }
serde_json = "1"
anyhow = "1"
async-trait = "0.1"
ulid = { version = "1", features = ["serde"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "process", "io-util"] }

[dev-dependencies]
tempfile = "3"
